export default {
    SET_INITIAL_CPU_GAME_OPTION: "SET_INITIAL_CPU_GAME_OPTION",
    SET_INITIAL_USER_GAME_OPTION: "SET_INITIAL_USER_GAME_OPTION",
    SET_SELECTED_USER_GAME_OPTION: "SET_SELECTED_USER_GAME_OPTION",
    SET_SELECTED_CPU_GAME_OPTION: "SET_SELECTED_CPU_GAME_OPTION",
    RESET_SELECTED_CPU_GAME_OPTION: "RESET_SELECTED_CPU_GAME_OPTION",
    RESET_SELECTED_USER_GAME_OPTION: "RESET_SELECTED_USER_GAME_OPTION",
    SET_TOTAL_BOARD_VALUES: "SET_TOTAL_BOARD_VALUESS",
    SET_CPU_BOARD_VALUES: "SET_CPU_BOARD_VALUES",
}